### ISSUE TITLE
Aslav commander does not rotate with the turret

### ISSUE THREAD

**Issue by CB11B** [discoADFU/Project_Uncut_Issues#100]
The commander when turned out does not rotate with the turret. (only the commander.)

![20171014232126_1](https://user-images.githubusercontent.com/30292648/31575647-509fa6d8-b137-11e7-9258-e4231d92b911.jpg)

**Comment by MontyBravo** [comment]
ASLAV is still WiP, Vehicle animations are being worked on

**Comment by MontyBravo** [comment]
Commander rotates with turret correctly, he stopped reading the quantum tunneling book
