### ISSUE TITLE
Helmets Not appearing (MTP new latest patch)

### ISSUE THREAD

**Issue by MLGMitchell** [discoADFU/Project_Uncut_Issues#105]
At certain angles and distances the Helmet that a unit is equipped with from the latest ADFU patch with AAF. It appears to not effect the hold style amp and amc helmets and only happen with the new mtp camo that I have seen so far. however it seems fine from far distances and very close up to the unit. I have also noticed that this happens a lot when the camera is above the unit looking down at it.

**Comment by TheLJFox** [comment]
Need repo steps and images on this issue

**Comment by MLGMitchell** [comment]
Haven't noticed it in a while but If I see it again I will let you know. Could possibly been fixed a while ago tbh

**Comment by TheLJFox** [comment]
Could not repo
