### ISSUE TITLE
Browning High Power MkII No Suppressor model for Vanilla Suppressor

### ISSUE THREAD

**Issue by AussieArchAngel** [discoADFU/Project_Uncut_Issues#110]
Browning doesn't show Vanilla suppressor attachment or Ace Flash Suppressor when attached to weapon.
![browning no attachment](https://user-images.githubusercontent.com/38751045/39295776-9b5faf72-4982-11e8-8ad5-76d804cfc190.jpg)
![browning vanilla suppressor](https://user-images.githubusercontent.com/38751045/39295781-9da8cc64-4982-11e8-953e-3c59256aead0.jpg)
![browning ace flash suppressor](https://user-images.githubusercontent.com/38751045/39295783-9ed4889e-4982-11e8-9358-4a45fce59504.jpg)

**Comment by MontyBravo** [comment]
Proxy wrangled back into its correct position.
