### ISSUE TITLE
TBAS + Belts?

### ISSUE THREAD

**Issue by Haydos4793** [discoADFU/Project_Uncut_Issues#112]
Only something minor however I noticed how the TBAS is using the MilGearPack mod as the base and then the AMCU texture on top. Given this, it would be nice to see some options for TBAS + Belts in the editor and in game seeing as the mod allows it. I see that the medic has the option, however the others do not.

As I said its only minor, however speaking from a current grunts perspective, I believe it would add a finishing feel to the armour and really replicate how ADF inf are equipping these days.

Hope this helps (And happy to be of help anywhere else if needed).

**Comment by MontyBravo** [comment]
Believe it or not, this exact issue is what kick started the QoL update we are in the middle of performing !

So yes, agreed 110%

**Comment by TheLJFox** [comment]
Implemented for all standard infantry units
