### ISSUE TITLE
Varying between versions.

### ISSUE THREAD

**Issue by Mikkelwriter** [discoADFU/Project_Uncut_Issues#114]
Hello. 
I have an issue that I think is with the newest incarnation of the mod (one with the ASLAV). Sometimes it will load correctly with the new vehicles, yet most of the time it will load as if it were the old mod. I have tried this with and without the old steam workshop link, and the optional extras link and the problem persists. 

I am not sure if any mods may be causing conflict; I have the RHS mods, as well as ACE and the NCS-NZDF mod.

Thank-you for taking the time to read this, if any more information is required I would be more than happy to provide it.

**Comment by TheLJFox** [comment]
@Mikkelwriter Can you run the current version of the mod and CBA together and see if the issue persists. If no issue, continue adding the other mods you use until a conflict arises.

**Comment by Mikkelwriter** [comment]
I've unloaded everything except CBA and this mod, the same issue presents itself.

**Comment by TheLJFox** [comment]
Are you viewing these differences within Eden, Zeus or Both?

**Comment by Mikkelwriter** [comment]
I've only had it switch when I restart games, but that is a rare occurrence now, I've viewed it in Eden and Virtual Arsenal, I can take some pictures if you wish.

**Comment by Mikkelwriter** [comment]
I've just had a thought, perhaps it isn't uninstalling the old mod correctly and the files are mixed in the pathway, I'm going to try un-subscribing and clearing the files before installing the new mod and I'll let you know the results.

**Comment by Mikkelwriter** [comment]
I have tried this and repeated it, it has worked so far.

**Comment by TheLJFox** [comment]
So after a complete uninstall of the old version, everything works now?

**Comment by Mikkelwriter** [comment]
yes, although I had to delete both mods in order to be rid of any files that stayed from the older version. Thank-you for your help as-well.

**Comment by TheLJFox** [comment]
All good mate, we got there in the end. Damn steam workshop for not doing its job
