### ISSUE TITLE
Classnames??

### ISSUE THREAD

**Issue by EvilInsid** [discoADFU/Project_Uncut_Issues#122]
hey guys ive searched everywhere for classnames for this mod.. havent found much. does anyone know where to find a classnames list of all items??

my email: m.hummer1998@gmail.com

**Comment by MontyBravo** [comment]
Some classnames have changed, however we will include a classnames.hpp in the next release

**Comment by MontyBravo** [comment]
Scracth that, Will update the Project_uncut_ALiVE.PDF to contain them all instead
