### ISSUE TITLE
Add bolt release catch animation to all F88/S/EF88 rifles

### ISSUE THREAD

**Issue by TheLJFox** [discoADFU/Project_Uncut_Issues#17]
(Pedal above and to the rear of magazine well) so animation of them “pressing” that is incorrect, instead should be recocking, by grabbing cocking handle and pull fully rearward before releasing.
https://drive.google.com/file/d/0B9l77euG3y63QkN0eFpSTGNMUWs/view

**Comment by MontyBravo** [comment]
Anim done
