### ISSUE TITLE
Duplicate F88’s available in the Arsenal

### ISSUE THREAD

**Issue by TheLJFox** [discoADFU/Project_Uncut_Issues#19]
![u5r8eg2](https://cloud.githubusercontent.com/assets/9318282/26538379/bd5f4c9e-4489-11e7-825f-deec3d57aeb1.jpg)

**Comment by MontyBravo** [comment]
Need to repo this !

**Comment by Azza276** [comment]
The Workshop Version doesn't appear to have this issue.

**Comment by MontyBravo** [comment]
Huh, closing then
