### ISSUE TITLE
Adjust vest RVmats to use vanilla ones

### ISSUE THREAD

**Issue by TheLJFox** [discoADFU/Project_Uncut_Issues#2]
![20170529145039_1](https://cloud.githubusercontent.com/assets/9318282/26537510/886c7918-4483-11e7-9dc8-9cad98a0fa4f.jpg)

**Comment by LJRam** [comment]
![20170529145039_1](https://cloud.githubusercontent.com/assets/9318282/26537499/77d26856-4483-11e7-8225-46d4f23495fa.jpg)

**Comment by MontyBravo** [comment]
RVMAT's Adjusted.
