### ISSUE TITLE
The EF88/F90 are missing a Foregrip (Integrated bipod)

### ISSUE THREAD

**Issue by TheLJFox** [discoADFU/Project_Uncut_Issues#29]
![umhf954](https://cloud.githubusercontent.com/assets/9318282/26538859/9089af40-448c-11e7-9b94-49c24c717472.jpg)

**Comment by AtreusTFD** [comment]
![20160927_105344](https://cloud.githubusercontent.com/assets/29057430/26573725/29d400ee-4562-11e7-8cb7-c42723868d85.jpg)

Example of bipod for interest or help.

**Comment by MontyBravo** [comment]
Going to mount the same podgrip that is on the Max to the EF88

**Comment by Azza276** [comment]
That being said... is it worth exploring creating the 3 different Grip/Bipod options for the EF-88 and making them bipod items?

![](http://www.thefirearmblog.com/blog/wp-content/uploads/2017/03/image1.jpg)

Also noting these little stubby ones are about too but not in the image above.

![](http://www.thefirearmblog.com/blog/wp-content/uploads/2017/03/oXxs9X1-660x444.jpg)

Maybe make the stubby one's attached by default, as in part of the parent model, but disappears and replaced by attached bipods?

**Comment by AtreusTFD** [comment]
^Solid Idea Azza

**Comment by MontyBravo** [comment]
Atatched Bipods wont work the way you would like.  Engine limitation.

**Comment by Azza276** [comment]
Ok Fair enough. :)

**Comment by MontyBravo** [comment]
Hold hold pending new EF88 model integration

**Comment by willithappen** [comment]
Added to new EF88 Model
