### ISSUE TITLE
EF88 Texture

### ISSUE THREAD

**Issue by AtreusTFD** [discoADFU/Project_Uncut_Issues#34]
Understandable if it is a placeholder but would suggest using the F90 skin, since they are basically the same weapon system. Current EF88 is all black FYI, also optic on it is a Spectre Elcan
https://armament.com/specterdr-1-4x

**Comment by MontyBravo** [comment]
The EF88 and F90 are currently being completely redone.
So the ones in at this time are placeholders.
As for the optics, I have seen Leo HAMR's, Acogs n all sorts of optics attached ?

**Comment by AtreusTFD** [comment]
Yeah most of the time RAR's In particular 1 and 2 are using Trijicon ACOG however most other units with the EF88 are given Specre Elcan. Also whilst deployed we use ACOG.

**Comment by Azza276** [comment]
Hey Atreus, how ya going mate. 

IRL, It'd be up to the individual Regiment what they use really, even on deployment, but the bog stock issue for most units is the SpecterDR, which will be made as well. Essentially all known optics in use, plan to be available in final release. And it'll be up to the mission makers which optics they want to use. ;)

**Comment by willithappen** [comment]
Updated as WIP for next build
