### ISSUE TITLE
Helmet (Airframe) vs OpsCore

### ISSUE THREAD

**Issue by AtreusTFD** [discoADFU/Project_Uncut_Issues#35]
Standard issue helmet current is the OpsCore one can that be changed to default for the placeable units.

**Comment by TheLJFox** [comment]
The placeable units have randomized helmets at this time which involves both OpsCores (6 Variants) and Airframes (2 variants). Whilst OpCores are standard issue for some units, Airframes are making their way to units with some being actively deployed overseas using them.
