### ISSUE TITLE
Bayonet Locking Lug

### ISSUE THREAD

**Issue by beno83au** [discoADFU/Project_Uncut_Issues#36]
Some weapon parts are white/missing textures on the F88, EF88 and F90 (mainly bayonet locking lugs, gas plugs, where the fore grip attaches to the barrel).

**Comment by MontyBravo** [comment]
The model in for the EF88, F90 is currently a placeholder/tester  a new version is being worked on at this time which will NOT have the missing textures (and look better)

**Comment by MontyBravo** [comment]
Closed Duplicate Issue
