### ISSUE TITLE
Machine gun Animation errors ?

### ISSUE THREAD

**Issue by MontyBravo** [discoADFU/Project_Uncut_Issues#39]
Odd floating part to all MG's happened in mission ?

**Comment by TheLJFox** [comment]
![20170603182658_1](https://cloud.githubusercontent.com/assets/9318282/26753777/5243bdc4-48b1-11e7-85bf-22d919b5f873.jpg)
![20170603182817_1](https://cloud.githubusercontent.com/assets/9318282/26753778/5244ce08-48b1-11e7-9ba7-e401a3d97d7e.jpg)

**Comment by MontyBravo** [comment]
Mod conflict with the defunct AAM Mod.
Closing
