### ISSUE TITLE
Airframe Shadow bug

### ISSUE THREAD

**Issue by MontyBravo** [discoADFU/Project_Uncut_Issues#40]
Right hand side of the airframe it has a sgadow issue streaching down across the player

**Comment by TheLJFox** [comment]
![20170603183357_1](https://cloud.githubusercontent.com/assets/9318282/26753792/90d26ef0-48b1-11e7-8862-0f9c71180b06.jpg)

**Comment by TheLJFox** [comment]
Fixed shadow LOD
