### ISSUE TITLE
F8AS-A1 Austeyr not visible in VENOM USMC (CUP) on certain passenger seats

### ISSUE THREAD

**Issue by Dolannn** [discoADFU/Project_Uncut_Issues#49]
As the title says, the weapon is not present on certain seats inside the Heli, unsure if this can be fixed on the ADFU End or if it's due to CUP whatsoever. 

Images provided:
https://gyazo.com/61455d96bef5e6ea7f6a37e7a4025761
https://gyazo.com/f7f08f27c0b91068997b465f633437ce

**Comment by MontyBravo** [comment]
That would be the animation for the seated pose.  Nothing we can do with ADFU.
