### ISSUE TITLE
F89 Minimi Fire Rate

### ISSUE THREAD

**Issue by Alldaboss** [discoADFU/Project_Uncut_Issues#50]
I feel like the fire rate is off and lower than it should be, the recoil on it also is a bit high, ive fired it before and its pretty easy to control its fire rate. It also dosent have a burst fire feature.

**Comment by Azza276** [comment]
According to the Army Website, https://www.army.gov.au/our-work/equipment-and-clothing/small-arms/f89-and-para-minimi the cyclic rate of the minimi is 800-900 rounds per minute. You will be able to compare by doing a 10 second burst and count the number of rounds fired times by 6. This will give you a good approximation of what it's doing in game. Just be aware the audio bites for an MG firing can sometimes sound a little off compared to the real thing.

For recoil, which positions are you referring to, Standing/Crouched or Prone. I can agree that the recoil may be a little high in the prone, but from standing/crouching, it feels a lot more manageable in game then the real thing... But yeah, right wrist fatigue to move the mouse to compensate is not as severe as the left arm fatigue firing it IRL.

**Comment by MontyBravo** [comment]
The burst fire feature was a left over from the inheritance, removeing it now.
additionally the weapon has a
reloadTime = 0.085;
So its foreing at around 705 RPM.  And yes, due to the nature of the game, the audio will be a tad off.  We will try to compensate as best we can.

**Comment by MontyBravo** [comment]
Fire rate adjusted.
Burst fire mode removed.
Recoil not adjusted as standing holding it and firing is not easy ;)
Hence the current recoil
