### ISSUE TITLE
Section/Unit Loadouts; Medical Items

### ISSUE THREAD

**Issue by Skyth3323** [discoADFU/Project_Uncut_Issues#51]
Adjustment of unit equipment (Medics having a billion bandages everywhere except the backpack.) and Section/Squad placements for Eden/Zeus.

**Comment by willithappen** [comment]
@Skyth3323 The issue here is due to ACE3 converting the Medkit and First Aid Kids in the units load out to Epinephrine, Morphine and Basic Bandages.

**Comment by willithappen** [comment]
@Skyth3323 Please also explain issue with 

> Section/Squad placements for Eden/Zeus.
http://i.imgur.com/76ltdR5.png
http://i.imgur.com/NRjo69O.png

**Comment by Skyth3323** [comment]
Sure, basically other mods have preset section placements for units, it'd be nice if ADFU could also incorporate this idea and have Squad/Section configs for easy use in Eden or Zeus.

**Comment by willithappen** [comment]
But we do? Thats what the two above screenshots show?

**Comment by Skyth3323** [comment]
Sorry, that's not what I'm seeing. https://steamuserimages-a.akamaihd.net/ugc/841458808200691823/D7EF615173DB4501CC5CF16E5E656FAF21D8610E/

**Comment by willithappen** [comment]
You'll need to press the "Groups" tab or F2 in the EDEN editor.

If you are using Zeus, it is the second button along the top. This is the same location for all mods and even vanilla assets locations of their groups.

If you still do not have these, please re-open the issue.
http://i.imgur.com/JowFv3j.png

**Comment by Skyth3323** [comment]
Can confirm I am a dingus. Please pardon my carelessness in performing basic instructions.

**Comment by willithappen** [comment]
<3
