### ISSUE TITLE
F88 Weapon System; Nameing convention + Suppressors

### ISSUE THREAD

**Issue by Alldaboss** [discoADFU/Project_Uncut_Issues#52]
Just a quick one, Not sure but allot of us know the F88 system as F88-SA1 and SA2 instead of how the wiki pages have it as F88S-A1 while defence pages reference them as F88A2, personnelly when i did my recruits we always had them named as F88 SA2 or SA1. Another point is the F88, F88S - A1 and F88S - A2 dont have the ability to have a suppressor of any kind fitted only BTBFAs (used when firing blanks) can be fitted. However the EF88 has the ability to be modified to support a suppressor.

**Comment by MontyBravo** [comment]
ok So F88 - SAx   easy to adjust.
I could have sworn the SA1 and SA2 could have the clip style suppressor !  Always welcome to be wrong tho, easy enough to remove as well !
As far as the BFA goes, we had though of including them, but not just yet ;)

**Comment by Alldaboss** [comment]
I guess in theory you could have a suppressor made for the F88, but defence never invested in the idea of doing that and just left it standard with its flash hider. A bit selling point of the EF88 is its modular system and the use of suppressors.

**Comment by MontyBravo** [comment]
F88-SAx Series renamed
Suppressors removed on F88-SAx series
