### ISSUE TITLE
Hemet LOD issue - headphones disappearing

### ISSUE THREAD

**Issue by WraithV** [discoADFU/Project_Uncut_Issues#69]
Opscore helmet airframe with headphones cover. 

Headphones disappear on 2nd LOD. Seems to be unique to this helmet.

![20170623211018_1](https://user-images.githubusercontent.com/29656154/27479989-95a9473e-5859-11e7-900a-dbf2700474fa.jpg)
![20170623211019_1](https://user-images.githubusercontent.com/29656154/27479990-95ae77e0-5859-11e7-8472-b04fab085328.jpg)

**Comment by MontyBravo** [comment]
Fixed - done
