### ISSUE TITLE
Helmet texture weirdness

### ISSUE THREAD

**Issue by Lookst** [discoADFU/Project_Uncut_Issues#70]
So videos explain things better than words so here's a video
https://vid.me/r4vZ

Watch the helmet on Rohan and the texture doing funky things. As far as I know I've only noticed this when inside vehicles (maybe even only helis) but I could be wrong.

**Comment by MontyBravo** [comment]
Attempting to Repo, turned up nothing.

Far far as I know, it was a temporary issue and resolved !
