### ISSUE TITLE
Tracer Colour.

### ISSUE THREAD

**Issue by Jazzadazza** [discoADFU/Project_Uncut_Issues#72]
Tracers on are green.  Australian army uses red tracers.

**Comment by discoADFU** [comment]
has been fixed https://github.com/discoADFU/Project_Uncut_Issues/issues/64

**Comment by Jazzadazza** [comment]
Legends, Monty told me to add it!

**Comment by discoADFU** [comment]
thats cool. dont stop adding stuff! :)
