### ISSUE TITLE
retexture - new TBAS T1 in AMP

### ISSUE THREAD

**Issue by discoADFU** [discoADFU/Project_Uncut_Issues#77]

**Comment by MontyBravo** [comment]
I dont believe tbas was ever done in AMP.  I believe khaki, tan, olive etc and DPCU, DPDU and AMCU ?
Or is thing just to give tacticool kids special butterflies ?  Which ok then !

**Comment by Azza276** [comment]
Yes they were. http://i.imgur.com/ahCRDKM.jpg

**Comment by discoADFU** [comment]
what vests do SF use? im only going by the tiers of TBAS which to my knowledge: 
T1 = SF
T2 = dismounted inf
T3 = mounted inf (what ours ingame are now)
