### ISSUE TITLE
create - facewear/eyewear like masks, shemags, balaclava and goggles

### ISSUE THREAD

**Issue by discoADFU** [discoADFU/Project_Uncut_Issues#78]
for SF and less obvious ones can also be used for regular infantry.

what facewear + eyewear combo we want, and what colours/camo is open to interpretation. something like:
-mask + sunglasses/shades
-balaclava + goggle
-shemag + sunglasses/shades
-ballistic protection glasses only
-shemag + ballistic glasses

**Comment by willithappen** [comment]
New facewear added as WIP for next build
