### ISSUE TITLE
create - M4 rifle

### ISSUE THREAD

**Issue by discoADFU** [discoADFU/Project_Uncut_Issues#79]
M4A5 in the following variants:
- M4 plain
- M4 w/ vertical foregrip
- M4 w/ angled foregrip
- M4 w/ GL

camos & colours:
- black
- tan
- green
- snakeskin camo
- hex desert camo
- woodland spray camo

attachments:
- Joint Rails support for sights
- Joint Rails support for IR laser/flashlight
- Joint Rails support for suppressors

**Comment by pmuenjohn** [comment]
Do we need that many variants, camouflages and colours?
I feel like the plain can be replaced with the AFG variant (Is there a way to make the VFG an attachment like RHS?)
Man, I like the M4 just as much as anyone but I don't want the VA to be filled with 24 different M4s.

**Comment by Azza276** [comment]
Agree, although I'm not too familiar with SF gear, most of the time I see guys just break the shape and colour with scrim, torn cams, etc. Most are standard black. Maybe just a Black and a Camo version, and then if there is enough demand for another particular variant, then it's looked at. :)

**Comment by discoADFU** [comment]
good point. I suppose it can be narrowed down to:

M4 w/ vertical foregrip
M4 w/ angled foregrip
M4 w/ GL

in black, desert camo and woodland camo

**Comment by willithappen** [comment]
Updated as WIP for next build
