### ISSUE TITLE
Front Foregrip on F88 is incorrect 

### ISSUE THREAD

**Issue by TheLJFox** [discoADFU/Project_Uncut_Issues#8]
Issue:
![xq5erej](https://cloud.githubusercontent.com/assets/9318282/26537979/be64e7a0-4486-11e7-8f94-b929895c26af.jpg)

F88S has correct hand grip
![nlx8gwg](https://cloud.githubusercontent.com/assets/9318282/26537924/734dddd0-4486-11e7-83e4-9dbb46c66baf.jpg)

**Comment by MontyBravo** [comment]
Hand anims unified
