### ISSUE TITLE
Browning HP Hammer to be locked back at all times.

### ISSUE THREAD

**Issue by Azza276** [discoADFU/Project_Uncut_Issues#82]
Based on the WIP images of the BHP, I recommend having the Hammer in the locked back (cocked) position. The only time the hammer goes forward is when firing (obviously) and when the there is a misfire (round didn't fire). (Also when there is no mag and you fire the action, but this is practically non-existent in Arma.)

Essentially whenever the weapon fires, the slide goes back and pushes back the hammer and locks it down... The trigger just releases the hammer (does not push it back first, the slide does that). Therefore the default state for the BHP which is loaded and cocked (ready to fire) is with the hammer locked back. Even with empty mag, the slide locks rearward anyway, so even on an empty mag you can't fire the action (letting the hammer go.)

**Comment by MontyBravo** [comment]
Wilco, Will just take a little time as is proveing slightly complicated !

**Comment by MontyBravo** [comment]
Animation adjusted - done
