### ISSUE TITLE
G3 AMC Uniform - Polygon out of place?

### ISSUE THREAD

**Issue by thraxjor** [discoADFU/Project_Uncut_Issues#83]
Hi guys,

here is a small detail i noticed in the Arsenal, where a polygon or two is out of place I think?

![arma 3 07 11 2017 - 19 35 49 01](https://user-images.githubusercontent.com/30072912/28062739-330fb1f4-6672-11e7-8e8c-8eb8e665bed2.png)
![arma 3 07 11 2017 - 19 35 53 02](https://user-images.githubusercontent.com/30072912/28062745-37433534-6672-11e7-97ae-e08c09c2d6fd.png)
side by side.
![g3_amc_uniform](https://user-images.githubusercontent.com/30072912/28062748-3a40b63a-6672-11e7-87d8-0aebc688d043.gif)

**Comment by willithappen** [comment]
Unfortunately you will notice the same behavior with the Vanilla G3 as this is a Bohemia asset. We cannot do anything to fix this as a result.
