### ISSUE TITLE
M4A5 issues

### ISSUE THREAD

**Issue by TommoAAF** [discoADFU/Project_Uncut_Issues#84]
A few issues.

The M4A5's in game name is M5A5.
The M4A5's inventory picture is a steyr, the SA2.
The M4A5 only takes 5.56mm 30rnd Steyr magazines, it's not compatible with other 5.56 mm magazines.

![20170712171850_1](https://user-images.githubusercontent.com/30107561/28106862-e7cdef82-6728-11e7-9e52-933ecadde96a.jpg)

![20170712172233_1](https://user-images.githubusercontent.com/30107561/28106871-eca8d4a4-6728-11e7-8b6c-6e3054f6ddc3.jpg)

**Comment by pmuenjohn** [comment]
More issues as of 0.1.2 beta
Front sight post doesn't work great with the ACO (Not really important)
Flat out doesn't work with the ERCO (Pretty important)
All the sights are skewed to the right by probably half a mm. (Not much of a problem, but quick fix)
Rail attachment point should be to the right hand side rail, so as to not mess with the handanim.
No Shadow LOD on the mesh

![107410_20170712174242_1](https://user-images.githubusercontent.com/14701221/28107181-ffd5ec64-6729-11e7-8763-e101f1bb37d8.png)
![107410_20170712174352_1](https://user-images.githubusercontent.com/14701221/28107185-0440fd7a-672a-11e7-952a-fd06485d6750.png)
![107410_20170712174434_1](https://user-images.githubusercontent.com/14701221/28107187-06ac81b0-672a-11e7-8ad9-b0a89b0aa538.png)

**Comment by willithappen** [comment]
Fixed ~~The M4A5's in game name is M5A5.
Fixed ~~ The M4A5's inventory picture is a steyr, the SA2.
Fixed ~~ The M4A5 only takes 5.56mm 30rnd Steyr magazines, it's not compatible with other 5.56 mm magazines.

WIP ~~ ERCO + ACO Scope issues still present.
