### ISSUE TITLE
M4A5 Model clipping + Inventory icon

### ISSUE THREAD

**Issue by MrMazza35** [discoADFU/Project_Uncut_Issues#86]
The rail attachments clip through the characters hand, most other AR weapons in arma attach right side of rail, ADFU M4 uses left side, suggest moving them to alleviate clipping issues possibly change hand hold to magazine? Also M4 inventory icon is a Steyr

![20170712223621_1](https://user-images.githubusercontent.com/30117864/28118492-9276764a-6754-11e7-883c-5aa5ce3bbab9.jpg)

**Comment by pmuenjohn** [comment]
Already mentioned in issue #84 
Of course, will be fixed as soon as possible.
Probably by moving the attachment point to the right, and/or giving the m4 an AFG or VFG.
Thanks for actually coming to the issues tracker though.
