### ISSUE TITLE
Ef88 Gl sight glitch

### ISSUE THREAD

**Issue by CB11B** [discoADFU/Project_Uncut_Issues#91]
When the texture for The ef88 gl red dot crosses over the barrel a white pixelation appears. I am not aimed down sight, my texture settings are set to high and my shadows are off, not sure if that helps, if you need to contact me my email is novinec.a@gmail.com, or CB11B on the AAF discord
![ef88_gla](https://user-images.githubusercontent.com/30292648/28368969-7a3aedc4-6cd9-11e7-8037-9c319be78c0f.png)

**Comment by MontyBravo** [comment]
Fixed, I believe, couldent repo it in the first place.
