### ISSUE TITLE
Broken Maximi texture in first person (V0.2 SF)

### ISSUE THREAD

**Issue by TacticalDropBear** [discoADFU/Project_Uncut_Issues#96]
Hello guys,
Here is an image gallery that displays the bug.
https://imgur.com/a/uD3VJ

Additional Info:
- Tested both with and without additional mods running(bug still present)
- I noticed this bug only occurs in first person.
- Bug occurs with and without weapon attachments

Thanks!

**Comment by MontyBravo** [comment]
repainted... correctly
